# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71babc6253d08f949b69d99497ab1ad89113146ab71d6a3cc77b06385012e098bb031bcf87740ebd8a0d02e97c958612d262c15337d15b71f396d041e4068f2f

test:
  secret_key_base: 3ebded1b0fcfc3c10dc90be99cacb3e7b479d8043889fa530780585a9ebc9d0127dcc3981303080d444c6e146f8ae9e3494fb2e4c8c2069248f4cb69ba5ac061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
